### ISSUE TITLE
Tag input not editable when empty

### ISSUE THREAD

**Issue by mrjosa** [Geta/Tags#35] opened 2016-04-22 09:32 UTC
We updated EPiServer to 9.8.0 and suddenly we can't add any new tags in an empty editor. On pages where tags had already been added we can edit and add new, but if we remove them all we can't add any new. Newly created pages can't add tags either.

We are running the latest version 2.1.9

Quite bothersome. Do you have any solution for this?

**Comment by mrjosa** [comment] 2016-04-24 20:54
Apparently it is the dijitPlaceHolder that is trapping the click into the input field. Not sure if this is an EPiServer change or something you can do something about?

**Comment by marisks** [comment] 2016-04-25 06:09
@mrjosa I could look at this issue later this week or beginning of the next week. 
But you can do pull request if you find solution.

**Comment by marisks** [comment] 2016-04-26 10:43
@mrjosa just tested on new Alloy tech project and it works. Tested in EPiServer version 9.8.0. and on 9.8.2.
Maybe the issue is related to another plugin or editor descriptor in your project?

**Comment by frederikvig** [comment] 2016-06-10 19:39
Closing this for now. Feel free to reopen if you encounter it again.

**Closed by frederikvig** 2016-06-10 19:39 UTC
