### ISSUE TITLE
Tag page with existing tag by mouse-click not working

### ISSUE THREAD

**Issue by orjhor** [Geta/Tags#16] opened 2015-03-11 10:50 UTC
When tagging a page with an existing tag by clicking the tag, EPiServer is not registering the textbox as changed, thus not saving the tag-property on "Save & publish".
This does not seem to be an issue if you are creating a new tag.

However, selecting the existing tag by using the up/down keys + Enter will trigger the textbox changed.

Tried with latest vanilla Alloy site and latest Geta.Tags version.

**Comment by frederikvig** [comment] 2015-03-24 20:25
Which version of EPiServer did you test this on?

**Comment by orjhor** [comment] 2015-03-25 06:47
I've had this problem since 7.19.1, but also in the later updates. I tested it today on the latest version (update 58) also. The issue is not consistent, as you can see in my attached .gif.
![demo](https://cloud.githubusercontent.com/assets/1080274/6819560/1ca6a232-d2c3-11e4-9b61-a6790946880c.gif)

**Comment by frederikvig** [comment] 2015-03-26 17:39
I tried reproducing this on a fresh Alloy site (EPiServer - update 58) without success (using Chrome). I think this might be browser related - have you had similar problems with the built in properties before?

**Comment by orjhor** [comment] 2015-03-27 07:19
I've tried IE 11 and Chrome (latest version, 41.0.2272.101).
I tried a fresh Alloy (with the latest update 58 Visual Studio template) also, with the exact same result. Also tried both WebForms and MVC just to rule that out, but with the same result.

This is me testing the latest Geta.Tags in a fresh Visual Studio Alloy-template running update 58 in Chrome:
[link to gif](https://dl.dropboxusercontent.com/u/62023471/demo2.gif)

**Comment by orjhor** [comment] 2015-03-27 07:19
I've tried IE 11 and Chrome (latest version, 41.0.2272.101).
I tried a fresh Alloy (with the latest update 58 Visual Studio template) also, with the exact same result. Also tried both WebForms and MVC just to rule that out, but with the same result.

This is me testing the latest Geta.Tags in a fresh Visual Studio Alloy-template running update 58 in Chrome:
[link to gif](https://dl.dropboxusercontent.com/u/62023471/demo2.gif)

**Comment by marisks** [comment] 2015-03-27 09:33
I could reproduce that behavior in Chrome. Can check next week for solution.

**Comment by marisks** [comment] 2015-04-23 09:02
Tried to solve it, but without any results. For some reason EPiServer time to time do not trigger change event. As this issue occurs only in some specific scenarios, I will not do more investigation, but we are open for contributions if solution found.

**Comment by robgha01** [comment] 2015-04-27 14:12
We have the same problem, but only on the live site with the same webbrowser "Chrome" however
it works in our local environment.

I tested with fiddler and no property changed request happens live the only requests that is made is "/getatags?term=te".

**Comment by timker** [comment] 2015-09-21 05:07
I'm also having with this issue this. 
One workaround is to add a pointless tag and then remove it.


tested on 
geta tags 1.0.4 and 2.0.3.0
EPiServer 7.19 and 8.8.0.0 Alloy
Chrome (45) & Firefox on a PC

**Comment by ezsearch** [comment] 2015-12-10 18:32
I can confirm the same. I am using the latest 2.4.1. The text box change trigger is not getting fired.

**Comment by marisks** [comment] 2016-04-12 13:12
Fixed by: #34

**Comment by jonizen** [comment] 2016-04-19 12:01
I can still recreate this issue. It seems to me that the problem occurs when you use the auto-complete to use an already existing tag and select it with the mouse. If you dont click in the tags container before clicking outside it, the change is not triggered. I also think if the auto-save occurs before you click in the tags container then tags save null. Just a thought :)

**Comment by marisks** [comment] 2016-04-19 12:19
@jonizen do you use latest version (2.1.9)? Also did you try to clear browser cache?

In latest version, save gets triggered on item selection from auto-complete list.

**Comment by jonizen** [comment] 2016-04-20 06:57
Yes, both. I can se your changes in #34 in my ClientResources. I tried on two different sites. To be clear, EPi should detect the change when i click (with the mouse) on an existing tag?

![animation1](https://cloud.githubusercontent.com/assets/1162489/14665752/ab6b68bc-06d5-11e6-894b-f02944b67704.gif)
![click-in-textbox-after-selection](https://cloud.githubusercontent.com/assets/1162489/14665755/b14df9e8-06d5-11e6-8bce-35227583d243.gif)
![on-enter-click](https://cloud.githubusercontent.com/assets/1162489/14665756/b449d86a-06d5-11e6-9392-0c4d0d9f3756.gif)

I attached 3 gifs. 
First with the issue i am having.
Second show if we click somewhere in the textbox the change is triggered
And the third when hitting enter it works.

**Comment by marisks** [comment] 2016-04-20 07:03
@jonizen Could you check in browser's developer tools how Geta.Tags/TagsSelection.js script under ClienResources looks like?
From gifs I see that this is old behavior before changes.

**Comment by joseftw** [comment] 2016-04-20 07:07
Hey, we are working on the same project...it looks like this
![snip_20160420090653](https://cloud.githubusercontent.com/assets/1232096/14666021/4bc46b1e-06d7-11e6-8856-d98c0bf60f24.png)

The problem occurs for me as well

**Comment by marisks** [comment] 2016-04-20 07:25
@joseftw it looks like the right version. Which EPiserver version do you have? Do you have any errors in browser console?

**Comment by joseftw** [comment] 2016-04-20 07:30
We are currently using
EPiServer.CMS.Core 9.0.3
EPiServer.CMS.UI 9.0.0
EPiServer.CMS.UI.Core 9.0.0
EPiServer.Framework 9.0.3

Do you think the problem will go away if we upgrade to the latest version of EPI?

**Comment by marisks** [comment] 2016-04-20 07:37
It works on my site with:
EPiServer.CMS.Core 9.6.1
EPiServer.CMS.UI 9.3.8
EPiServer.CMS.UI.Core 9.3.8
EPiServer.Framework 9.6.1

I am not sure if upgrade helps, but you could try - upgrade is needed anyway :)

**Comment by jonizen** [comment] 2016-04-20 08:32
I upgraded the site from:
EPiServer.CMS.Core 9.0.3
EPiServer.CMS.UI 9.0.0
EPiServer.CMS.UI.Core 9.0.0
EPiServer.Framework 9.0.3

To:
EPiServer.CMS.Core 9.8.1
EPiServer.CMS.UI 9.4.4
EPiServer.CMS.UI.Core 9.4.4
EPiServer.Framework 9.8.1

And it works perfectly! So a higher version of UI and the problem is gone. Thank you for all the help and quick replies!

**Comment by marisks** [comment] 2016-04-20 08:33
That's great. I will close an issue as it works in latest versions.

**Closed by marisks** 2016-04-20 08:33 UTC
